### ISSUE TITLE
@silverstripe

### ISSUE THREAD

**Issue by Martimiz** [praxisnetau/silverstripe-module-starter#2]
Hi,
Btw: If you're writing SilverStripe admin module, you might want to add the @silverstripe module and implement its features in webpack.config.js

This makes it real easy to use SilverStripe components and other stuff in your React modules. Found out this week, working on my first SilverStrip Admin module try-out :-).  

Martine

**Comment by Martimiz** [comment]
Sorry, actually it is `@silverstripe/webpack-config`

**Comment by colintucker** [comment]
Thanks for letting me know. This module really is about getting your foot in the door with SS4 modules, webpack, Sass compiling and such. Other than that, it doesn't really make any assumptions about what other components or technologies you'll be using for your module (e.g. React). I'll leave that up to the developer to decide what to add. 😃

**Comment by Martimiz** [comment]
Ok, I see your point :) I just assumed, at least for the admin section, that @silverstripe would give good integration with silverstripe backend react, as it was made just for that. 

But probably in that case module versioning would have to follow SilverStripe versioning as well. 

EDIT: and then again probably not :)

Maybe just mentioning it in your documentation would be an option?

Martine
